### ISSUE TITLE
博主,为什么首页会内存崩溃

### ISSUE THREAD

**Issue by wenhaojie** [WinterChenS/my-site#17]
博主,为什么首页会内存崩溃

**Comment by poc9999** [comment]
什么错误  OOM吗？

**Comment by jinshihui88** [comment]
这个问题怎么解决？

**Comment by hongjun500** [comment]
我这边只是发现因为图片的原因导致的，具体还在排查

**Comment by AtticusMA** [comment]
查到什么原因了么，我也是第一次遇见奔溃这种事情

**Comment by AtticusMA** [comment]
就是因为发布博客的时候分类选择了作品，作品就是图片，然后前端js展示的时候因为是图片加载错误，因为设置图片服务器吧

**Comment by louhangxun** [comment]
你们没看如何部署吗？里面说了如果使用图片上传服务的话要用七牛云储存，你们也可以把储存地址换成服务器地址，或者注册一个七牛云
