### ISSUE TITLE
springboot 怎样跟 durid 集成的？

### ISSUE THREAD

**Issue by HelloWorld521** [WinterChenS/my-site#2]
为什么我找不到你项目中的 DataSourceConfig 和 DruidDBConfig 这种类似的配置

**Comment by WinterChenS** [comment]
这个是不需要配置的，请问你是哪里看到需要这样配置的呢？

**Comment by HelloWorld521** [comment]
https://www.cnblogs.com/a8457013/p/7804512.html   这个的 dateSource 配置
后者这个 https://www.jianshu.com/p/9c58c84e285a     **DruidConfiguration**
网上很多资料都是要配置的，可以问下你是怎么处理的吗？

**Comment by WinterChenS** [comment]
可以看我的一篇博客：https://blog.csdn.net/winter_chen001/article/details/80010967，因为我使用了Druid的springboot-starter，所以不需要额外的使用javaconfig配置，区别就在这里。
