### ISSUE TITLE
找不到sun.misc包

### ISSUE THREAD

**Issue by wenbinai** [WinterChenS/my-site#34]
![image](https://user-images.githubusercontent.com/45991406/72526325-2b907900-38a1-11ea-8058-80acf0497370.png)
尝试将将java11转为java8仍然没有解决

**Comment by wenbinai** [comment]
重新测试了,java8可以,解决,但java11还是会报错

**Comment by NepSouls** [comment]
那个包在jdk9后就删除了，简单改动后可以在openjdk11运行

**Comment by louhangxun** [comment]
这个非常简单，你把sun公司的这个包换成阿帕奇的
 //return new BASE64Encoder().encode(encryptedBytes);
  return String.valueOf(Base64.encodeBase64(encryptedBytes));
另一个同理

**Comment by Yonggie** [comment]
那个包已经在高版本的java中废弃了。就用了个加密功能，可以用新函数改动下删掉misc相关的就行了。
