### ISSUE TITLE
jar包部署后的访问地址是什么

### ISSUE THREAD

**Issue by louhangxun** [WinterChenS/my-site#36]
我按照作者说的http://localhost:8080/这样访问，我在本地idea运行时可以访问，放上服务器之后就报错，无法访问什么的

**Comment by WinterChenS** [comment]
要保证服务的防火墙开放了这个端口或者关闭防火墙

**Comment by WinterChenS** [comment]
可以试一下在服务器的命令行中输入命令：
`curl 127.0.0.1:8080`
