### ISSUE TITLE
本地运行成功 ，七牛云也配置好了，但是图片显示不出来，大哥，求解

### ISSUE THREAD

**Issue by TyquanTao** [WinterChenS/my-site#40]
@WinterChenS  
![MAZVX1FI XQC`S UVQZGP7S](https://user-images.githubusercontent.com/48404566/80163962-4bef7280-860a-11ea-8eaa-68ccbb78ed7a.png)

**Comment by WinterChenS** [comment]
现在搞定了吗？

**Comment by WeiShitao** [comment]
首页加载不出来图片+1

**Comment by 374362356** [comment]
我也存在这个问题，请问怎么解决呢
