### ISSUE TITLE
大佬 这里是不是写错了 写成递归了 应该是用logDao的delete吧

### ISSUE THREAD

**Issue by Dios314** [WinterChenS/my-site#59]
![image](https://user-images.githubusercontent.com/45736371/147055760-f1265413-e80f-4dfc-8080-71129e7ea796.png)
![image](https://user-images.githubusercontent.com/45736371/147055837-d70cbf6b-d98c-4bcf-8f9c-eb927d7bb49f.png)

**Comment by WinterChenS** [comment]
@Dios314 欢迎提pr
