### ISSUE TITLE
大佬 为啥sql导入失败

### ISSUE THREAD

**Issue by pigeon-xu** [WinterChenS/my-site#61]
-- ----------------------------
DROP TABLE IF EXISTS `t_options`;
CREATE TABLE `t_options` (
  `name` varchar(32) NOT NULL DEFAULT '',
  `value` varchar(1000) DEFAULT '',
  `descrip
[Msg] Finished - Unsuccessfully
--------------------------------------------------

**Comment by WinterChenS** [comment]
你使用的方式不对吧
