### ISSUE TITLE
There is a  stored XSS on the article page.

### ISSUE THREAD

**Issue by PoppingSnack** [WinterChenS/my-site#74]
There is a  stored XSS on the article page.
1. On the "article publish" page，attackers can post an article containing a malicious script.
path: http://localhost:8089/admin/article/publish
![image](https://user-images.githubusercontent.com/48405266/225189015-dc683e90-fab9-4fc5-a983-a74cb07f4106.png)

2. This XSS vulnerability can be triggered by attackers reading articles in the blog article interface.
path: http://localhost:8089/blog/article/29
![image](https://user-images.githubusercontent.com/48405266/225190003-8cc236f7-5895-48fa-b065-88e389425a2f.png)

**Comment by WinterChenS** [comment]
fix it in: #77

**Comment by dossihounkpenoudji10** [comment]
https://github.com/WinterChenS/my-site/issues/74#issue-1624622333
