### ISSUE TITLE
大佬, 评论字数的校验代码在哪里呢?

### ISSUE THREAD

**Issue by lq-0519** [WinterChenS/my-site#81]
<img width="1282" alt="image" src="https://github.com/WinterChenS/my-site/assets/54232407/ddf98aa3-6e3f-4854-b40c-c70bade43c47">

如图, 想修改这个字数限制, 找不到位置呢, 请教

**Comment by WinterChenS** [comment]
@lq-0519 
https://github.com/WinterChenS/my-site/blob/master/src/main/resources/templates/site/comments.html
第85行
